### ISSUE TITLE
Issues after merging 

### ISSUE THREAD

**Issue by aihooo444** [MiSTer-devel/Arcade-Pacman_MiSTer#18]
-Birdiy image is upside down and doesn't load fully
-Mr.TNT won't load
-Ms.Pacman sprites are funky (it's like it is trying to be pacman and ms pacman at same time
-Pacman Plus makes some weird noises and doesn't boot up properly

**Comment by sorgelig** [comment]
Update MiSTer binary. Issue is not related to core.
