### ISSUE TITLE
dipsw in mra

### ISSUE THREAD

**Issue by eubrunosilva** [MiSTer-devel/Arcade-Pacman_MiSTer#21]
Hi

looking at birdiy:
	<switches default="EF,FF,11">
		<dip bits="4"     name="Cabinet" ids="Upright,Cocktail"/>
		<dip bits="16,17" name="Coinage" ids="2c/1cr,1c/1cr,1c/2cr,Free Play" values="3,1,2,0"/>
		<dip bits="18,19" name="Lives" ids="3,4,5,6"/>
		<dip bits="20"    name="First Pattern" ids="Hard,Easy"/>
		<dip bits="21"    name="Teleport Holes" ids="On,Off"/>
	</switches> 

name and ids its easy to get from mame. 
but how do i get switches default and dip bits?
Thanks

**Comment by sorgelig** [comment]
Defaults - no idea. set what do you like.
dip bits are from mame as well. it's first and last bit assigned for function. Up to 64 bits for dips are currently supported (8 bytes). Pacman uses 3 bytes (in0,in1,dipsw1) - it's core (arcade) dependent size;

**Comment by eubrunosilva** [comment]
ups the code i wrote here wasnt displayed.

https://github.com/mamedev/mame/blob/master/src/mame/drivers/pacman.cpp#L1734
you have here the input for birdiy

PORT_DIPNAME( 0x03, 0x01, DEF_STR( Coinage ) )      PORT_DIPLOCATION("SW:1,2")
how do you get the 16,17 bit for this? 

also the defaults, how do you get the FF,FF,E9 ?
you have here 3 default values for two dipnames.

**Comment by sorgelig** [comment]
pacman uses 4x8 dips. 4th isn't used and always FF.
0x03 is mask in 3rd byte which is bits 16-17.
Use all FF for default as safe value. User will be able to setup the dips manually.

**Comment by eubrunosilva** [comment]
about pacman club.
Its supposed to use: INPUT_PORTS_START( mspacman )
that should have
<dip bits="20,21" name="Bonus Life After" ids="10000,15000,20000,None"/>
and not
<dip bits="20,21" name="Bonus Life After" ids="20000,40000,80000,None"/> (also i didn't found this values in pacman.cpp)

is this core different?

my line of tough was grab dip config for each "input sets" and all of the alternatives and other parent games that use this "input set" i would place this configs in mra...

**Comment by sorgelig** [comment]
probably something missing in your message. I don't understand it.

**Comment by sorgelig** [comment]
btw, pacman club dip switches in mame is totally wrong. Or there are different pacman club roms. The dips in pacman club.mra are correct

**Comment by eubrunosilva** [comment]
yeah not easy to explain... and i didnt do it well...

GAME( 1989, clubpacm,  0,        woodpek, **mspacman**, pacman_state,  empty_init,    ROT90,  "Miky SRL", "Pacman Club / Club Lambada (Argentina)", MACHINE_SUPPORTS_SAVE | MACHINE_NOT_WORKING )

The bold part should be the input (inputs,dips) used in the game. The same as mspacman.
But if its wrong. i am changing them in my db for the ones you have for pacman club :)

**Comment by sorgelig** [comment]
you can try mspacman dips on club and see how it will work

**Comment by eubrunosilva** [comment]
hi
no need index="1" in Super Glob?

**Comment by sorgelig** [comment]
if no index="1" then ROM is compatible with Pacman ROM
