### ISSUE TITLE
More input buttons needed for non pacman games

### ISSUE THREAD

**Issue by dazzer69** [MiSTer-devel/Arcade-Pacman_MiSTer#23]
Super Glob for instance needs buttons to jump and call elevators. Many thanks.

**Comment by sorgelig** [comment]
They are the same as Start P1 and Start P2. 
They are hardwired even on real HW.

**Comment by dazzer69** [comment]
I stand corrected. Thanks, sorgelig.
Are there any plans for "per mra" configuration saving as opposed to per core?

**Comment by sorgelig** [comment]
Yes, i'm planing to do it

**Comment by dazzer69** [comment]
Well done. It works like a charm. Would it be an easy task to add support for "The Glob/Beastie Feastie". Both are later variants of Super Glob (and pacman rom swaps) but with far better playability.

**Comment by sorgelig** [comment]
i don't know yet. I'm not dedicated to arcades actually.

**Comment by sorgelig** [comment]
i close the issue as it's fixed. 
You may post your request in Arcade thread in MiSTer forum.
