### ISSUE TITLE
Graphic corruption on VGA output with IO board

### ISSUE THREAD

**Issue by bootsector** [MiSTer-devel/Arcade-Pacman_MiSTer#38]
A small graphic corruption right below the high score label shows up with my VGA CRT monitor connected through IO board:

https://i.imgur.com/Dfk0xcE.jpg

This doesn't happen with HDMI output.

**Comment by sorgelig** [comment]
it's weird as HDMI output takes the video coming to VGA.

**Comment by bootsector** [comment]
Sorry for this mis-report. This actually happens on my MiSTer connected to CRT only but not on my second MiSTer connected to the HDMI. It's something related to files on SD/USB. I'm closing this and will look for the solution in the forums.
