### ISSUE TITLE
No "HIGH SCORE" Text in latest core build

### ISSUE THREAD

**Issue by ZReport** [MiSTer-devel/Arcade-Pacman_MiSTer#5]
There is no "HIGH SCORE" text label in the latest core build for Pac-Man.

**Comment by silvestru64** [comment]
Why arcade pacman latest core has no "HIGH SCORE" and no "CREDIT" ? which file do we need to edit to make it/them show?

**Comment by zakk4223** [comment]
For the purposes of helping in tracking this down: If you run a pacman rom using the Crush Roller core it properly displays the 'high score' and 'credit' text. The dip switch config is incorrect, though (which is to be expected).

**Comment by silvestru64** [comment]
zakk4223 thanks for your kind help. That seems to work but then the tunnel walls seem to be highlighted light blue, and when eating the ghosts the score is red, not light blue. Also when the ghosts are in scare mode they turn light blue and flash dark blue instead of dark blue and flash white.
But thanks anyway.

**Comment by sorgelig** [comment]
try latest release

**Comment by silvestru64** [comment]
HI,
I thank you for taking your time to help me.
I did try the latest core of pacman. In fact I tried all of them. I also tried injecting the a.pacman.rom file  into the rbf file.
I saw a video on NML32 you tube and the file is dated 20171109 but its not present in GitHub release.

Again thanks for your time


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by zakk4223** [comment]
He means the core that was released about 30 minutes ago ;)

I just tried it; credit and top score text now appears for me.

**Comment by silvestru64** [comment]
YESSSSS.
Sorry I didn't realize that there was an update.
This is the best present for my birthday today. Thanks to you all.
