### ISSUE TITLE
Pac-Man Plus does not launch the correct ROM

### ISSUE THREAD

**Issue by dmotowylak** [MiSTer-devel/Arcade-Pacman_MiSTer#50]
Pac-Man Plus runs some alternative hack of Pac-Man by default (standard blue maze, but different font).
However, if I load an alternative ROM (Arcade/Alternatives/PacMan Plus) and pick "PacMan Plus (HBMAME)", I am getting the right game.

Validated on 3 different builds.

**Comment by sorgelig** [comment]
if i remember right someone stated opposite and swapped them...

**Comment by dmotowylak** [comment]
I see this under closed issues. Perhaps this was impacting the main game?  The problem
I reported is only for PacMan Plus.  The main arcade game works fine. 

PacMan Plus should have the teal maze and Coke can as the first “fruit” item. 

@ZReport ZReport commented on Nov 18, 2018 •
edited 
The latest core build is using the teal palette from Pac-Man Plus instead of the original blue palette

**Comment by Thelypody** [comment]
I wanted to report this issue, but it seems it is a known one.
Launching "Pacman Plus - HBMame.mra" boots something which looks and plays like an actual Pac-Man Plus game, but reading the file shows that it loads data from an HBMAME rom of Puck-Man instead of the actual MAME "pacplus" rom.
